- name: Setup ebs nodes
  hosts: ebs_nodes
  tasks:
    - name: Install required packages
      ansible.builtin.package:
        name:
          - lvm2
          - open-iscsi
          - parted
        state: latest
    - name: Enable iscsi and start it 
      ansible.builtin.systemd:
        name: iscsid
        state: started
        enabled: yes